// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SameApi.Db.DbContexts;

#nullable disable

namespace SameApi.Db.Migrations
{
    [DbContext(typeof(SameApiDbContext))]
    partial class SameApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LKP_ProfessionDaoLKP_SchoolDao", b =>
                {
                    b.Property<int>("ProfessionsId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolsId")
                        .HasColumnType("int");

                    b.HasKey("ProfessionsId", "SchoolsId");

                    b.HasIndex("SchoolsId");

                    b.ToTable("LKP_ProfessionDaoLKP_SchoolDao");

                    b.HasData(
                        new
                        {
                            ProfessionsId = 1,
                            SchoolsId = 1
                        },
                        new
                        {
                            ProfessionsId = 2,
                            SchoolsId = 8
                        },
                        new
                        {
                            ProfessionsId = 3,
                            SchoolsId = 8
                        },
                        new
                        {
                            ProfessionsId = 4,
                            SchoolsId = 8
                        },
                        new
                        {
                            ProfessionsId = 5,
                            SchoolsId = 2
                        },
                        new
                        {
                            ProfessionsId = 6,
                            SchoolsId = 2
                        },
                        new
                        {
                            ProfessionsId = 9,
                            SchoolsId = 3
                        },
                        new
                        {
                            ProfessionsId = 7,
                            SchoolsId = 3
                        },
                        new
                        {
                            ProfessionsId = 8,
                            SchoolsId = 4
                        },
                        new
                        {
                            ProfessionsId = 10,
                            SchoolsId = 5
                        },
                        new
                        {
                            ProfessionsId = 11,
                            SchoolsId = 5
                        },
                        new
                        {
                            ProfessionsId = 12,
                            SchoolsId = 6
                        },
                        new
                        {
                            ProfessionsId = 13,
                            SchoolsId = 7
                        });
                });

            modelBuilder.Entity("SameApi.Model.CommentDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserDaoId");

                    b.ToTable("SameApi_Comment");
                });

            modelBuilder.Entity("SameApi.Model.LKP.LKP_GenderDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKP_SameApi_Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("SameApi.Model.LKP.LKP_ProfessionDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKP_SameApi_Profession");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Informaticien/ne CFC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronicien/ne CFC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Automaticien/ne CFC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Polymécanicien/ne CFC"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Employé/e de commerce CFC"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gestionnaire du commerce de détail CFC"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dessinateur/trice en bâtiment CFC"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Installateur/trice sanitaire CFC"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Maçon/ne CFC"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Graphiste CFC"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bijoutier/ère CFC"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Assistant/e en soins et santé communautaire CFC"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Assistant/e socio-éducatif/ve CFC"
                        });
                });

            modelBuilder.Entity("SameApi.Model.LKP.LKP_SchoolDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKP_SameApi_School");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CFPT - École d'informatique"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CFPC - École de Commerce Raymond-Uldry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CFP Construction - Site André-De-Ternier"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CFP Construction - Site du Rhône"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CFP Arts - École d'arts appliqués"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CFPSa - Centre de Formation Professionnelle Santé"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CFPSo - Centre de Formation Professionnelle Social"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CFPT - École d'électronique et de mécanique"
                        });
                });

            modelBuilder.Entity("SameApi.Model.PostDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Comments_count")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Likes_count")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserDaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserDaoId");

                    b.ToTable("SameApi_Post");
                });

            modelBuilder.Entity("SameApi.Model.UserDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenderDaoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberFollowers")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionDaoId")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolDaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenderDaoId");

                    b.HasIndex("ProfessionDaoId");

                    b.HasIndex("SchoolDaoId");

                    b.ToTable("SameApi_User");
                });

            modelBuilder.Entity("LKP_ProfessionDaoLKP_SchoolDao", b =>
                {
                    b.HasOne("SameApi.Model.LKP.LKP_ProfessionDao", null)
                        .WithMany()
                        .HasForeignKey("ProfessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SameApi.Model.LKP.LKP_SchoolDao", null)
                        .WithMany()
                        .HasForeignKey("SchoolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SameApi.Model.CommentDao", b =>
                {
                    b.HasOne("SameApi.Model.CommentDao", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("SameApi.Model.PostDao", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("SameApi.Model.UserDao", "UserDao")
                        .WithMany()
                        .HasForeignKey("UserDaoId");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("UserDao");
                });

            modelBuilder.Entity("SameApi.Model.PostDao", b =>
                {
                    b.HasOne("SameApi.Model.UserDao", "UserDao")
                        .WithMany()
                        .HasForeignKey("UserDaoId");

                    b.Navigation("UserDao");
                });

            modelBuilder.Entity("SameApi.Model.UserDao", b =>
                {
                    b.HasOne("SameApi.Model.LKP.LKP_GenderDao", "GenderDao")
                        .WithMany()
                        .HasForeignKey("GenderDaoId");

                    b.HasOne("SameApi.Model.LKP.LKP_ProfessionDao", "ProfessionDao")
                        .WithMany()
                        .HasForeignKey("ProfessionDaoId");

                    b.HasOne("SameApi.Model.LKP.LKP_SchoolDao", "SchoolDao")
                        .WithMany()
                        .HasForeignKey("SchoolDaoId");

                    b.Navigation("GenderDao");

                    b.Navigation("ProfessionDao");

                    b.Navigation("SchoolDao");
                });
#pragma warning restore 612, 618
        }
    }
}
