<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>178caa09-02fe-4c7f-8045-380bd957697f</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SameApi.Business\SameApi.Business.csproj" />
	</ItemGroup>

</Project>